### ISSUE TITLE
Demo dashboard is empty

### ISSUE THREAD

**Issue by RongxinZhang** [unlock-protocol/unlock#6519] opened 2020-04-16 15:28 UTC
**Describe the bug**
The current demo dashboard does not display anything.

**To Reproduce**
1. Go to 'https://app.unlock-protocol.com/dashboard/'

**Expected behavior**
Not sure what it's suppose to show

**Screenshots**
<img width="1162" alt="Screen Shot 2020-04-16 at 11 28 19 AM" src="https://user-images.githubusercontent.com/3782456/79475243-6b1c4d80-7fd5-11ea-8214-85c9c1cf7496.png">

**Desktop (please complete the following information):**
 - OS: MacOS Latest
 - Browser: chrome

**Comment by julien51** [comment] 2020-04-17 18:14
Thanks for reaching out.
Do you have a crypto wallet like MetaMask? I was able to reproduce if my web browser does not have one in it.
We are pushing a fix for this.

**Comment by julien51** [comment] 2020-04-17 18:15
Here is what you should see after the fix has been puhsed (1 hour from now). Please confirm!

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/17735/79600838-cd4c7f80-80b5-11ea-8bdc-4dfbd9a697fd.png">

**Comment by julien51** [comment] 2020-04-20 13:26
@RongxinZhang Could you please confirm this is fixed now?

**Comment by julien51** [comment] 2020-04-21 17:41
Ok, I'll consider this closed as I am not able to reproduce anymore ;)

**Closed by julien51** 2020-04-21 17:41 UTC
