### ISSUE TITLE
Add a loading spinner when user chooses to purchase access

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1383] opened 2019-02-04 14:21 UTC
**Is your feature request related to a problem? Please describe.**
There is a bit of delay between when a user clicks on the purchase button and when the lock shows that it has started confirming. It's not a huge delay, but long enough that they may wonder if their click had any effect. Adding a spinner or similar progress indicator here would smooth out the UX a bit.

**Describe the solution you'd like**
Intermediate state between purchase button and confirming lock that immediately shows that the click has been registered.

**Describe alternatives you've considered**
An alternative would be to immediately and optimistically change state to confirming. This would achieve the same result and would not require any additional design work.

**Comment by julien51** [comment] 2019-02-04 14:24
I think this is due to how we currently send transactions.
Basically, on one side we push the transaction through `walletService` and on the other site, `web3Sevice` pulls the transaction from the chain. Unfortunately though there is a non negligible time during which `web3Sevice` currently does not know what the transaction is about which means that the UI cannot show what is going on.

I think I have an idea on how to solve this! I'll keep you posted!

PS: this is a problem for *all* kinds of transactions.

**Comment by julien51** [comment] 2019-02-28 15:50
@cnasc Is this still happening?

**Comment by cellog** [comment] 2019-02-28 15:52
I implemented this in my hooks experiment. It's a UI issue, we just need to change the state of the transaction to pending the instant it is sent and the lock will change visual state. I'm happy to take this on in the non-hooks paywall

**Comment by julien51** [comment] 2019-03-15 18:33
@cellog What is the status of this in the paywall app?

**Comment by cellog** [comment] 2019-03-15 18:35
This is next on my plate, once #2114 is merged

**Comment by cellog** [comment] 2019-03-15 18:39
dupe of #1458

**Closed by cellog** 2019-03-15 18:39 UTC
