### ISSUE TITLE
Checkout Builder: Changing a Modal Header Image Icon under Configure the Basics Using a URL not working

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12559] opened 2023-08-15 14:44 UTC
**Describe the bug**
When a user attempts to change a Modal Header Image Icon under Configure the Basics by inserting an image URL, the Modal Header Image Icon remains the default Unlock logo. When an image file is uploaded, the Modal Header Image Icon changes to what is saved.

**To Reproduce**

1. Go to Checkout Builder
2. Go to Configure the basics
3. Click on the Change image icon CTA
4. Click on 'Insert image URL'
5. Insert an image URL
6. See the Modal Header Image Icon does not reflect the image of the image URL inserted

**Expected behavior**
When users click the 'Change image icon' CTA under 'Configure the Basics' in Checkout Builder and insert an image URL, the Modal Header Image icon should be the image from the URL.

**Comment by searchableguy** [comment] 2023-08-31 12:26
duplicate of earlier issue.

**Closed by searchableguy** 2023-08-31 12:26 UTC
