### ISSUE TITLE
Inconsistent expiration from the subgraph

### ISSUE THREAD

**Issue by gjeanmart** [unlock-protocol/unlock#6836] opened 2020-08-11 20:39 UTC
**Describe the bug**

 A newly created key has a correct expiration when calling directly the method `keyExpirationTimestampFor(_keyOwner)` but the subgraph returns `0` 

- **Lock:** [`0xcef3433e4f71124133ee4f08a317beff79b8555c`](https://etherscan.io/address/0xcef3433e4f71124133ee4f08a317beff79b8555c)
- **Key owner:** `0x7d4a43b60da2445299ef37fbcd986981edb87546`

<img width="1436" alt="Screenshot 2020-08-11 at 15 43 49" src="https://user-images.githubusercontent.com/506784/89945782-31c1ba80-dc22-11ea-90d2-fac6c2235575.png">

- **Subgraph:** [unlock (mainnet)](https://thegraph.com/explorer/subgraph/unlock-protocol/unlock)
- **Query:**

```graphql
{
  keys (where: {lock: "0xcef3433e4f71124133ee4f08a317beff79b8555c" owner: "0x7d4a43b60da2445299ef37fbcd986981edb87546"}) {
    id
    keyId
    owner {address}
    expiration
    createdAt
  }
}
```

<img width="1436" alt="Screenshot 2020-08-11 at 15 42 07" src="https://user-images.githubusercontent.com/506784/89945776-2ec6ca00-dc22-11ea-9a44-3b3e9ecaea34.png">

**To Reproduce**

Cannot find a way to reproduce this.

**Expected behavior**

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
 
- [Transaction](https://etherscan.io/tx/0x1a04eb1248eaff59f4058eacf52a97cfd93dca778be9328d8f4caf2596891ac1)

**Comment by julien51** [comment] 2020-08-12 22:18
I looked further and the only thing that I see which could have been the cause of this is that this transaction seems to have been replaced while none of the other has been https://etherscan.io/tx/0x1a04eb1248eaff59f4058eacf52a97cfd93dca778be9328d8f4caf2596891ac1

<img width="683" alt="image" src="https://user-images.githubusercontent.com/17735/90073851-fb3e7b00-dcc7-11ea-9b2b-ad79177ce874.png">

My understanding is that you sent this transaction?

**Comment by julien51** [comment] 2020-08-14 12:53
Redeploying the subgraph to see if this solves the issue: https://thegraph.com/explorer/subgraph/unlock-protocol/unlock?version=pending

**Comment by julien51** [comment] 2020-08-15 20:24
The graph is now fully redeployed but it still shows an expiration of 0 for that key. I am really puzzled. I'll keep digging.

**Comment by gjeanmart** [comment] 2020-08-24 15:57
After manually purchasing the subscription for this recipient `purchaseFor`, the subgraph is now fixed and return the right expiration timestamp. Mystery...

**Comment by julien51** [comment] 2020-10-03 13:32
Let's close this for now. I really suspect an isse with The Graph which might bave been fixed?

**Closed** 2021-11-21 03:33 UTC
