### ISSUE TITLE
Web3Service createLock inputsHandler is outputting invalid type for expirationDuration and maxNumberOfKeys on lock creation

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2102] opened 2019-03-15 14:43 UTC
when the ~~storageMiddleware receives a saved lock~~ Web3Service receives a `createLock` call to its `inputsHandler`, it is not changing `expirationDuration` and `maxNumberOfKeys` to number values. This causes a plethora of prop type failures throughout the app. Setting them to number values will fix this.

```diff
    this.inputsHandlers = {
      createLock: async (transactionHash, contractAddress, params) => {
        // The annoying part here is that we do not have the lock address...
        // Since it is not an argument to the function.
        // We will 'guess' it again using generateLockAddress
        // knowing that this may create a race condition another lock creation pending transaction
        // exists.
        const newLockAddress = await this.generateLockAddress()
        this.emit('transaction.updated', transactionHash, {
          lock: newLockAddress,
        })

        if (params._maxNumberOfKeys === MAX_UINT) {
          params._maxNumberOfKeys = UNLIMITED_KEYS_COUNT
        }

        this.emit('lock.updated', newLockAddress, {
          transaction: transactionHash,
          address: newLockAddress,
+          expirationDuration: +params._expirationDuration,
-          expirationDuration: params._expirationDuration,
          keyPrice: Web3Utils.fromWei(params._keyPrice, 'ether'), // Must be expressed in Eth!
+          maxNumberOfKeys: +params._maxNumberOfKeys,
-          maxNumberOfKeys: params._maxNumberOfKeys,
          outstandingKeys: 0,
          balance: '0', // Must be expressed in Eth!
        })
      },
    }
```

**Comment by akeem** [comment] 2019-03-16 16:26
@cellog would you mind adding a description around how I reproduce what you are seeing? Its been a bit since I have worked on storage middleware but these two attributes should be outside of the sphere of the object's influence as it should only capture the lock owner's address, address, and name

**Comment by cellog** [comment] 2019-03-16 16:34
I was deceived by the stack trace in redux dev tools, this goes higher up the food chain, thanks for bearing with me!

**Comment by akeem** [comment] 2019-03-16 16:51
no worries, just asked because I wasn't exactly sure what was going on

**Comment by julien51** [comment] 2019-03-21 01:09
So, closing I guess @cellog ?

**Comment by cellog** [comment] 2019-03-21 01:50
no, someone still needs to do the PR that has that diff, master is still erroneous

**Comment by cnasc** [comment] 2019-03-21 13:14
I'll do this momentarily

**Closed** 2019-03-22 12:07 UTC
Labels: p-2
