### ISSUE TITLE
Paywall rendering a bit weird on non-responsive pages (iOS)

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#1235] opened 2019-01-25 22:46 UTC
Paywall rendering appears amiss on iPhone for non-responsive pages. 

**To Reproduce**
Visit http://projects.mombartz.com/unlock/ on recent iphone with recent version of iOS 

**Expected behavior**
Paywall sizing an details sized somewhat relative to content on the hosting page

**Screenshots**
![image from ios](https://user-images.githubusercontent.com/44215/51776723-5ef25a80-20c8-11e9-8548-10ad1b476354.png)

**Smartphone (please complete the following information):**
 - OS: iOS
 - Browser [e.g. stock browser, safari] Safari

**Additional context**

**Comment by akeem** [comment] 2019-01-25 22:47
@benwerd would you mind updating this to ensure that all of the details are correct?

**Comment by cnasc** [comment] 2019-01-28 14:35
This may be a Safari issue in general, I notice that the wallet missing message renders too low on desktop Safari

<img width="1448" alt="screen shot 2019-01-28 at 9 34 51 am" src="https://user-images.githubusercontent.com/9300702/51842971-13b29480-22e0-11e9-91aa-7a10c331d4c6.png">

**Comment by cnasc** [comment] 2019-01-28 16:24
OK, if we set a Safari-specific attribute in a meta tag in the iframe head[1], it fixes the paywall sizing. The downside is that if we set that on the iframe, it messes with the parent non-responsive page...

![img_8c070a1923ab-1](https://user-images.githubusercontent.com/9300702/51850126-1d8fc400-22ef-11e9-9a16-c06cc2b0fe85.jpeg)

[1] https://bitsofco.de/ios-safari-and-shrink-to-fit/

**Comment by cnasc** [comment] 2019-01-28 16:56
@julien51 and I confirmed that this occurs on both iOS and Android. The root cause is that the site itself is not responsive, and there isn't a clean way to make the iframe be responsive when the site is not. I think this is a `wontfix`; the solution to having a responsive paywall is to have a responsive site.

**Closed by cnasc** 2019-01-28 16:56 UTC
Labels: design, frontend, p-2
