### ISSUE TITLE
Sending emails when keys/tickets have been confirrmed

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#5441] opened 2019-12-10 15:10 UTC
In the context of ticket purcahses, we should be able to send an email to the person who purchased a key, when that purchase is confirmed so that they can sign it and get a QR code.

**Comment by akeem** [comment] 2019-12-10 15:39
@julien51 to ensure that I understand the intended flow of the feature I have a couple of follow up questions.

After the purchase transaction is confirmed, is the intention that the person will receive an email directing them to the key chain page to sign or is this a custom page related to the specific event?

What is the use case attempting to be solved? Is it around customers being uncertain if their purchase has been successful or Is this to address that the key for the lock (event) may not appear upon the keychain for a few a minutes.

**Comment by julien51** [comment] 2019-12-10 19:37
Thanks for the question!

> After the purchase transaction is confirmed, is the intention that the person will receive an email directing them to the key chain page to sign or is this a custom page related to the specific event?

I think we need to keep the message "as generic" as possible, so I believe the message should be along the lines of "Your key purchase for lock XYZ was successful! you can view it in your keychain where you can get a QR code to assert its ownership..." 

> What is the use case attempting to be solved? Is it around customers being uncertain if their purchase has been successful or Is this to address that the key for the lock (event) may not appear upon the keychain for a few a minutes.

The use case is to make sure that users who have purchased a key to a lock for an event are reminded that they can get a QR code, since it can indeed happen minutes (or hours!)  after they actually purchased...

**Comment by akeem** [comment] 2020-02-04 14:26
As this feature has been shipped with the release of nudge, i'll close this issue.

**Closed by akeem** 2020-02-04 14:26 UTC
