### ISSUE TITLE
Show a "check your wallet overlay" in paywall

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4383] opened 2019-08-08 15:19 UTC
When purchasing a key or waiting for the user to enable, we should show a "check your crypto wallet" overlay to the UI as Metamask sometimes only shows a very small icon change rather than open a full pop up.

**Comment by cellog** [comment] 2019-08-08 15:26
dupe of #3093?

**Comment by julien51** [comment] 2019-08-12 21:45
Overlaps for sure but this is specifically for the paywall, while that other issue is for the "enable".

**Comment by cnasc** [comment] 2019-08-19 15:20
Looking into this right now for purchases. It's easy enough to launch the overlay when the purchase button is clicked. I think we have to handle 2 cases for dismissing the overlay:

1. new transaction - the presence of a new transaction implies that we don't need the overlay anymore.
2. `Error: "purchase failed"` - this will happen when the user rejects the transaction in MetaMask, so we should also dismiss the modal in that case.

We can parse error postmessages for the second case. In the first case, I think we need to introduce a new postmessage to tap into the `transaction.new` event from `WalletService`.

**Comment by cellog** [comment] 2019-08-19 16:25
Any time a submitted transaction is received, dismiss the modal. No need for a new postmessage

**Closed** 2019-08-20 19:58 UTC
Labels: p-2
