### ISSUE TITLE
State is being lost between pages

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#451] opened 2018-10-31 00:04 UTC
It looks like localStorage syncing isn't working as expected. I thought this was something in the code I was working on but it seems to be in master. As a result, it's very difficult to test keys or demo.

**Comment by julien51** [comment] 2018-10-31 00:55
Could you tell me more about how to reproduce?

**Comment by julien51** [comment] 2018-10-31 20:16
@benwerd ?

**Comment by benwerd** [comment] 2018-10-31 20:53
Sorry - it's that the contracts had been changed but hadn't recompiled, so the app and what was going on behind the scenes didn't match up. We can probably close this issue, but I think I'll open an issue to better handle changes to the underlying contract code (and maybe change the documentation to reflect this).

**Comment by benwerd** [comment] 2018-10-31 21:00
That said, now I've gone in and tried to test demo, things are still screwy. Is master working for you?

**Comment by julien51** [comment] 2018-10-31 21:18
Yes. But please describe what you're seeing so we can maybe fix things?

**Comment by benwerd** [comment] 2018-10-31 21:22
A few things. I've actually been wondering if I somehow have the wrong version of `Unlock.sol`.

* Upon creating a lock, I was getting an error saying that `createLock` expected 3 parameters but was getting 4. I commented out the first parameter, which is new.
* I can now create locks. But localStorage doesn't persist, and I think they're not saving properly to the chain. If I click to the demo page and back, the locks are gone.
* The demo link was broken, because lock.address is no longer populated. Similarly, the code preview is broken. Both work again if I move from using lock.address to lock.transaction.

**Comment by julien51** [comment] 2018-10-31 21:41
Ohhh i see what is going on and it makes me think we need integration tests.

@nfurfaro did indeed change the createLock signature by removing the
keyReleaseMechanism param.

This also means we need to handle errors when locks couldn't be created (
which would have been triggered by this bug)

I can look into these issues later today!

**Comment by benwerd** [comment] 2018-10-31 21:45
OK. And I think there's more to change (eg address vs transaction). I'll submit a PR here on the front end just to fix the obvious errors, but there's more to do. I agree that we need integration tests and can look at that.

**Comment by julien51** [comment] 2018-10-31 23:46
We are now reverting #446, which I believe is the root cause. I will first work on adding integration tests before we add that back. Closing this issue an opening 2 new ones: #458 and #459.

**Closed by julien51** 2018-10-31 23:46 UTC
Labels: bug
