### ISSUE TITLE
Deployment fails using USDC

### ISSUE THREAD

**Issue by wonderwomancode** [unlock-protocol/unlock#10948] opened 2023-02-02 20:37 UTC
**Describe the bug**
When trying to deploy a lock on Polygon mainnet with unlimited time and using USDC it fails.

**To Reproduce**
1. Go to create Lock
2. Network Polygon
3. Set currency as USDC 
4. Get and approve the  transaction in wallet
5. Transaction fails

**Expected behavior**
Deployed lock

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome 107.0.5304.121
<img width="993" alt="Screenshot 2023-02-01 at 3 27 42 PM" src="https://user-images.githubusercontent.com/18197239/216443523-62f8e14b-4e1b-4355-9033-4e56592c945c.png">

**Additional context**

I believe right before I sent this transaction I switched networks from Mumbai to Polygon Mainnet

Response 
transaction={"from":"0xFf4eC2057A4180A4Cd18FDEA144e53245e39869D","to":"0xE8E5cd156f89F7bdB267EabD5C43Af3d5AF2A78f","data":"0x487a8a760000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000001246eadde43000000000000000000000000ff4ec2057a4180a4cd18fdea144e53245e39869dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000fa8781a83e46826621b3bc094ea2a0212e71b230000000000000000000000000000000000000000000000001bc16d674ec80000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000024436f696e6261736520436f6d6d65726365203c3e20556e6c6f636b2050726f746f636f6c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: Address: low-level delegate call failed","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000027416464726573733a206c6f772d6c6576656c2064656c65676174652063616c6c206661696c656400000000000000000000000000000000000000000000000000"}

**Comment by julien51** [comment] 2023-02-02 20:56
I went thru these steps and I was able to send a transaction:

```
1. Go to create Lock
2. Network Polygon
3. Set currency as USDC 
4. Get and approve the  transaction in wallet
```

I suspect you changed network on the confirmation screen before submitting the transaction?

**Comment by julien51** [comment] 2023-02-07 19:08
Closing as we are not able to reproduce. Please provide more details and a way to reproduce if you want to re-open

**Closed by julien51** 2023-02-07 19:08 UTC
Labels: frontend
