### ISSUE TITLE
browser/integration testing possibilities

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#842] opened 2018-12-23 18:23 UTC
This article goes over many possibilities:

https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2018-f68950900bc3

**Comment by julien51** [comment] 2018-12-24 14:50
Closing as dupe of #195 ;) Let's try to limit the number of open issues...

**Closed by julien51** 2018-12-24 14:50 UTC
