### ISSUE TITLE
Paywall Embed Scrolling

### ISSUE THREAD

**Issue by smombartz** [unlock-protocol/unlock#1094] opened 2019-01-17 20:29 UTC
## Description
A user can still scroll and view the entire content even though the page should be locked.

## To Reproduce
http://projects.mombartz.com/unlock/

## Expected Behavior
Page should be locked and user should not be able to scroll

**Comment by cellog** [comment] 2019-01-19 21:08
browser? os? thanks

**Comment by cellog** [comment] 2019-01-19 21:16
looking at the source, it looks like staging is running a really old version of the paywall. It's still loading unlock.js instead of paywall.min.js. This is not a bug in master, but in deployment perhaps?

I can't reproduce the bug using the demo page from master in any browser on Mac OS X, but can reproduce the problem in any browser, for the reason that staging is at least 2 weeks out of date on the paywall front.

**Comment by cellog** [comment] 2019-01-19 21:17
alternately: Sascha, can you go to the dashboard on staging, and click on the Show embed code and re-copy the snippet into your local site? It's possible that you just haven't updated it since the changes were made?

**Comment by cellog** [comment] 2019-01-19 21:19
Confirmed. Spotted in the source for project.mombartz.com/unlock/

```html

		<!-- Include this script in the <head> section of your page -->
		<script src="https://staging.unlock-protocol.com/static/unlock.js"></script>
		<meta name="lock" content="0x715B4a5c8F3512C24f1F9F32472a08921CB83d58" />
```

This should be:

```html

		<!-- Include this script in the <head> section of your page -->
		<script src="https://staging.unlock-protocol.com/static/paywall.min.js" data-unlock-url="https://staging.unlock-protocol.com"></script>
		<meta name="lock" content="0x715B4a5c8F3512C24f1F9F32472a08921CB83d58" />
```

**Comment by smombartz** [comment] 2019-01-20 18:19
ooops. totally did not update it. [working now](http://projects.mombartz.com/unlock/) :)

**Comment by cellog** [comment] 2019-01-20 19:38
closing as fixed

**Closed by cellog** 2019-01-20 19:38 UTC
Labels: p-1
