### ISSUE TITLE
Ouvre-Boite blog doesn't recognize TrustWallet on iOS, doesn't scroll

### ISSUE THREAD

**Issue by bmann** [unlock-protocol/unlock#1241] opened 2019-01-26 07:14 UTC
**Describe the bug**
Opening Ouvre-Boite in TrustWallet (copy / paste URL from Twitter, paste into URL bar in TrustWallet) displays "Need Account", and doesn't let me scroll to see if I need to click on something and do something else. 

**Expected behavior**
I assume some sort of sign in with my wallet.

**Screenshots**

will add from my phone later

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS 12.1
 - Browser: TrustWallet
 - Version: 1.1440.0

**Comment by bmann** [comment] 2019-01-27 05:14
![GitHawk Upload by bmann](https://i.imgur.com/UY0aJUN.jpg)

Here’s the screenshot. 

I’m a big fan of TrustWallet — it is used widely.

**Comment by julien51** [comment] 2019-01-27 19:39
cc @cellog @akeem Does it look like the same issue that we're facing with Coinbase's Wallet app?

**Comment by julien51** [comment] 2019-01-27 19:39
Also I was able to install on Android and seeing the same issue.

**Comment by akeem** [comment] 2019-01-28 15:47
Referencing #1158 as they are related

**Comment by cellog** [comment] 2019-01-29 13:58
The scrolling being disabled is by design, as it hides the underlying content. The wallet not working is not by design, but we are making real progress on this front, stay tuned!

**Comment by cellog** [comment] 2019-02-09 01:28
@bmann the fix is pending PR review and a deploy from staging to production, stay tuned

**Comment by cellog** [comment] 2019-02-10 02:24
fix is live in staging, but unfortunately you can't test it yet since TrustWallet only supports mainnet. When we push, we'll definitely ping this bug.

**Comment by julien51** [comment] 2019-03-01 14:06
We're waiting for a new deploy to production to check this but it should be fixed.

**Comment by cellog** [comment] 2019-03-22 17:09
confirmed fixed in my testing, but let's re-check on Tuesday after the next deploy. I will optimistically close this issue :)

**Closed by cellog** 2019-03-22 17:09 UTC
Labels: frontend, p-2
