### ISSUE TITLE
smart-contracts/build needs to be in .gitignore

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#469] opened 2018-11-02 14:07 UTC
I'm getting this nonsense whenever I test things:

![image](https://user-images.githubusercontent.com/98250/47919888-fdcf3800-de86-11e8-9d6a-5a755711f4ba.png)

(the .idea folder is what webstorm uses, that would also be nice to have in .gitignore, but that can be dealt with later)

**Comment by julien51** [comment] 2018-11-02 14:09
Unfortunately this is not that simple. Duplicate of #363 ;)

**Closed by julien51** 2018-11-02 14:09 UTC
